# Generated by Django 3.2.7 on 2021-09-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quantity',
            new_name='qauntity',
        ),
    ]
