# Generated by Django 3.2.7 on 2021-09-07 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Order', '0002_rename_quantity_cart_qauntity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='qauntity',
            new_name='quantity',
        ),
    ]
